### ISSUE TITLE
Throw inside a function suppressed

### ISSUE THREAD

**Issue by jescalan** [webpack/tapable#10]
Coming from webpack, but I assume the origin is here in tappable, let me know if this would be better filed elsewhere!

If you add a plugin function and there is an error inside that function which would cause a throw, there is no handling. The callback is simply never called and webpack exits without compiling or throwing an error. A try/catch wrapper around the plugin function when it's invoked would take care of this cleanly :grin:

**Comment by andreypopp** [comment]
Could be solved by #11

**Comment by maximandrews** [comment]
I got some issues with silent crash on thrown error too.

`webpack@4.41.2`

Repo to reproduce: https://github.com/maximandrews/tapableThrownErrorIssue

**Comment by maximandrews** [comment]
Should I submit new issue?

**Comment by sneko** [comment]
@maximandrews where do you stand with this issue?

I'm having a webpack plugin doing:
```
compiler.hooks.afterEmit.tapAsync('SentryCliPlugin', callback);
```

But the callback is randomly called... I suspect something that is silent (because retrying with exact same code and it's so random). I hope to find the issue :)
