### ISSUE TITLE
Can we remove tap from hook？

### ISSUE THREAD

**Issue by wangzongxu** [webpack/tapable#109]
```js
var hook = new SyncHook(['param'])
var fn = param => console.log(param)

hook.tap('example', fn)
hook.call('frist')
// frist

setTimeout(() => {
   hook.remove(fn)
}, 3000)
```

**Comment by wangzongxu** [comment]
> Why? I can't undestand, also it is internal module for webpack, what is use case using this without webpack?

Because I using it in my Vue  Component, 
When I need to notify multiple components，
I need to add a tap when each component is mounted，
and need to remove a tap when each component is destroyed，

But I can't find anything as good as tapable for handling the flow of events.

I wanted to submit PR, but the 'lib/ hookcodefactory.js' file seemed too hard to understand.

**Comment by montogeek** [comment]
How are you using this with Vue components?

**Comment by wangzongxu** [comment]
> How are you using this with Vue components?

```js
const hook = new SyncHook()

// After a while
hook.call()

// dialog-a.vue
export default {
  methdos: {
     someMethod(){}
  }
  created() {
    hook.tap('If the dialog appears', this.someMethod)
  }
  destroyed() {
      // I want to remove it...
  }
}
```

**Comment by erasermeng** [comment]
https://github.com/webpack/tapable/issues/71#issuecomment-419377713

@wangzongxu

**Comment by sokra** [comment]
Due to internal optimizations done which depends on the taps called, it would be very inefficient to remove plugins. Therefore it it's not in the API. Avoid removing plugins.

Note that tapable is optimized for a call flow like: 1. attach to hooks, 2. call hooks at lot.
It's not an general purpose event emitter.

You could still handle your use case this way:

``` js
const hook = new SyncHook()

// After a while
hook.call()

const hookMethods = new Set();
hook.tap("dialog-a", () => for(const m of hookMethods) m());

// dialog-a.vue
export default {
  methdos: {
     someMethod(){}
  }
  created() {
    hookMethods.add(this.someMethod);
  }
  destroyed() {
    hookMethods.delete(this.someMethod);
  }
}
```

**Comment by Hypercubed** [comment]
@sokra Actually this is a real shame.  tapable has a great API that's useful outside webpack.  Lacking the ability to remove a tap really diminishes it's value.

**Comment by dabanlee** [comment]
why don't you use event hub?

```js
const eventHub = new Vue()

export default {
    created() {
        eventHub.$on('some-action', this.addTodo)
    },
    destroyed() {
        eventHub.$off('some-action', this.addTodo)
    },
    methods: {
        addTodo() {},
    },
}
```

**Comment by wangzongxu** [comment]
> why don't you use event hub?
> 
> ```js
> const eventHub = new Vue()
> 
> export default {
>     created() {
>         eventHub.$on('some-action', this.addTodo)
>     },
>     destroyed() {
>         eventHub.$off('some-action', this.addTodo)
>     },
>     methods: {
>         addTodo() {},
>     },
> }
> ```

因为当应用变得复杂的时候，tapable覆盖的场景更全面

**Comment by keifergu** [comment]
need this feature

**Comment by keifergu** [comment]
@wangzongxu I find a method to remove tap:
```javascript
var hook = new SyncHook(['param'])
var fn = param => console.log(param)

hook.tap('example', fn)
hook.call('frist')
// frist

setTimeout(() => {
   removeTapFromHook(hook, 'example');
}, 3000)

// remove
function removeTapFromHook(hook, tapName) {
    const index = hooks.taps.findIndex(tap => tap.name === tapName);
    if (index > -1) {
        hooks.taps.splice(index, 1);
    }
}

```

We only need remove the tap from the private variable `taps`.

**Comment by sokra** [comment]
That's private.

But anyway if you do that call `hook._resetCompilation()` to update the generated code.
