### ISSUE TITLE
Support for promises in async plugin apply strategies

### ISSUE THREAD

**Issue by andreypopp** [webpack/tapable#11]
ES2015 Promise is a standard now and Node.js is shipping with them enabled. With
the proposed (and now closer to being a standard) `async/await` syntax the
support for promises will be even stronger across the ecosystem. Another benefit of
promises is that they make handling errors much easier as user code doesn't need
to propagate `error` argument of callbacks explicitly.

I propose adding support for promises for async plugin applying strategies in
Tapable in a backward compatible way. Both for provider and consumer code paths.

That would enable Promise based API for plugins for Webpack and also a
way to convert Webpack codebase in the future to Promise based async primitives.

If you are ok with an idea I'm eager to start implementing a draft of the
proposal. What do you think?

**Comment by jantimon** [comment]
Had to write a custom wrapper for the html-webpack-plugin. 
Would really prefer if tappable would offer it directly.

**Comment by pi0** [comment]
@andreypopp @jantimon You may try [tappable](https://github.com/pi0/tappable) project which adds promise support to tapable 👻

**Comment by sokra** [comment]
new major supports promises
