### ISSUE TITLE
I am curious what is the point of these lines?

### ISSUE THREAD

**Issue by dmitriyaa** [webpack/tapable#113]
https://github.com/webpack/tapable/blob/ffc660840d2814b00a3e5e00cecb09519136bd37/lib/Hook.js#L41

```
this.compile = this.compile;
this.tap = this.tap;
this.tapAsync = this.tapAsync;
this.tapPromise = this.tapPromise;
```
I am not very good at OOP and don't know its patterns, but it looks a bit redundant for me.

**Comment by milottit** [comment]
It is apparently

**Comment by sokra** [comment]
These lines are important for performance reasons. We later reassign these properties. To avoid keeping the v8 Hidden Map from changing during the lifecycle of the class we assign these properties in the constructor to initialize the Hidden Map correctly.

**Comment by dmitriyaa** [comment]
Oh, makes sense now, thanks for the clarification!
