### ISSUE TITLE
Why HookCodeFactory generated code?

### ISSUE THREAD

**Issue by milottit** [webpack/tapable#114]
Please, could you explain why HookCodeFactory is generating code?

**Comment by evilebottnawi** [comment]
Why should he not do this? Can you tell me why you are using this module, since it is for internal use in webpack?

**Comment by sokra** [comment]
It is generating code to create a function which is calling all attached plugins. The function depends on the number and type of the plugins. By creating a custom function the v8 is able to inline calls to plugins into the monomorphic callsides. This would not be possible when looping over an array of plugins (which creates polymorphic callsides).

**Comment by evilebottnawi** [comment]
Answer above
