### ISSUE TITLE
arrow function in string can't transpile  

### ISSUE THREAD

**Issue by lzxue** [webpack/tapable#119]
https://github.com/webpack/tapable/blob/747a66766f8be92eead47f312f39dc84c00ff054/lib/HookCodeFactory.js#L58

I need use this lib for IE 11, but some Arrow function in string  can't  transpile by  babel


**Comment by evilebottnawi** [comment]
What is use case?

**Comment by lzxue** [comment]
> What is use case?

https://github.com/antvis/L7/blob/master/packages/layers/src/core/BaseLayer.ts#L77

i use in  a visualization project

**Comment by evilebottnawi** [comment]
I think it is impossible, it is internal module for webpack

**Comment by lzxue** [comment]
> I think it is impossible, it is internal module for webpack

This design pattern is suitable for data management and component expansion，so can you solve this problem?  I will be very grateful to you.

**Comment by sokra** [comment]
It's only used like 5 times in the generated code, so feel free to send a PR.

but make sure to only change the generated code, do not change all arrow function in this lib. This can be handled by transpilation.

**Comment by lzxue** [comment]
I tried to change the arrow function to a normal function, but it has scope problems. So I developed a new library instead of tapable in L7
