### ISSUE TITLE
Why use _call and call in Hook class?

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [webpack/tapable#133]
![image](https://user-images.githubusercontent.com/22312092/89988519-3cc42b80-dcb2-11ea-9c2b-ca0a23ff9425.png)

I cannot understand why use two methods _call and call, and could remove _call、_callAsync and _promise?

Who can tell me why?

**Comment by Mr-jiangzhiguo** [comment]
I guess with `_*` methods is the initial value, when need reset, it will assignment to without `_` methods

**Comment by evilebottnawi** [comment]
For architecture reasons? Please read code and look at logic, https://github.com/webpack/tapable/blob/master/lib/Hook.js#L130, keep them between compilations
