### ISSUE TITLE
Semantics of factory is correct?

### ISSUE THREAD

**Issue by brizer** [webpack/tapable#136]
https://github.com/webpack/tapable/blob/fa54822199203163a13b5bf7e403abc118ce3a87/lib/AsyncSeriesWaterfallHook.js#L27

As far as I can see, a factory is a function to return a instance, for example:

```
//use factory to new a class
const oraFactory = function (options) {
    return new Ora(options);
};
//export factory function
module.exports = oraFactory;
```

So `new Facroty` is reasonable？

**Comment by sokra** [comment]
A factory is an abstract design pattern. One way to implement it is a simple function. Another way is a class with a factory method. There are more.

More general it's about delegating the task of creating an instance to something else.

**Comment by brizer** [comment]
Thank you.
