### ISSUE TITLE
i use tapable singlely in my project,but in my webpack,"node_modules" folders  has no compile.

### ISSUE THREAD

**Issue by PoisonSnowFlying** [webpack/tapable#158]
does this library have ES5 version

**Comment by alexander-akait** [comment]
What is the error?

**Comment by PoisonSnowFlying** [comment]
the compiled code for online env. in some lower version browser,make some mistakes.so i need the compiled tapable code

**Comment by alexander-akait** [comment]
sorry, it is impossible, we don't support outdated browsers for this package

**Comment by PoisonSnowFlying** [comment]
OK, I understood this problem now, so  I wrote an asynchronous waterfall flow control method. but  still thanks!
