### ISSUE TITLE
Is there a way to unapply a plugin?

### ISSUE THREAD

**Issue by richardscarrott** [webpack/tapable#2]
Webpack applies many plugins by default e.g.

```javascript
compiler.apply(
    new JsonpTemplatePlugin(options.output),
    new FunctionModulePlugin(options.output),
    new NodeSourcePlugin(options.node),
    new LoaderTargetPlugin("web")
);
```

I'd like to, for example, use a different `JsonpTemplatePlugin` which handles error callbacks however I'm unable to remove the current one meaning I have to monkey patch the `JsonpTemplatePlugin` class... Is there a better way to achieve this?

**Comment by sokra** [comment]
Nope.

But the quoted plugins can be disabled with the `target` option.

**Comment by richardscarrott** [comment]
I did notice that but it looks like it'll error out if an unrecognised target is set...

**Comment by sokra** [comment]
I think you can provide a function which applies your custom plugins: https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L151

**Comment by richardscarrott** [comment]
Ah yes, thank you!

**Comment by arusakov** [comment]
Hi, @sokra 

There is no a way to ```plugout``` something after plugin (example for webpack):
```
compiler.parser.plugin('call fn', function () {
// ...
});
```
What do you think about adding ```plugout``` method for public API
