### ISSUE TITLE
Why `copyProperties` in applyPluginsParallelBailResult1 ?

### ISSUE THREAD

**Issue by chandlerprall** [webpack/tapable#22]
Trying to understand what's going on in the various pieces of code and can't figure out why `copyProperties` is used in `applyPluginsParallelBailResult1`? What properties are expected to be passed around on the callback?

**Comment by domfarolino** [comment]
Wouldn't mind knowing this as well. wondering the same thing actually

**Comment by chandlerprall** [comment]
I console logged the keys that get copied, the majority are `stack`, `missing`, and `log`. The `copyProperties` function is a huge bottleneck but it doesn't appear to be avoidable without a restructure of Tapable.

**Comment by guox191** [comment]
I'm wondering too

**Comment by sokra** [comment]
This was removed in the new major version
