### ISSUE TITLE
Question: Why using Array.prototype.slice

### ISSUE THREAD

**Issue by domfarolino** [webpack/tapable#23]
I noticed in `lib/Tapable.js` there are several calls to `Array.prototype.slice.call(arguments, ..)` example [here](https://github.com/webpack/tapable/blob/master/lib/Tapable.js#L58). I'm just curious as to why this is done when the `arguments` object is an array, and as such has `slice` in its `[[Prototype]]` chain.

Is it some sort of an optimization? Is a call to `Array.prototype.method.call(...)` faster than `someArray.method()`?

**Comment by TheLarkInn** [comment]
Tbh we would love a benchmark system to can hook into the one we just added on webpack/webpack if you could highlight the perf wins we will take a PR for sure

**Comment by domfarolino** [comment]
Welllll I just discovered that `arguments` inside a function is not really an array. In fact it seems that the only properties `arguments` and `Array.prototype` have in common is `Symbol.iterator` and `length`. `Array.prototype` doesn't even exist in its `[[Prototype]]` chain so the current code is entirely necessary.

<img width="325" alt="screen shot 2017-01-20 at 11 33 02 am" src="https://cloud.githubusercontent.com/assets/9669289/22158329/bce71476-df09-11e6-8182-3390fa05aab6.png">

With that being said, but still on the topic of perf, some research indicates that a good ol' `for (...)` loop will be considerably faster than `Array.prototype.forEach` so I wouldn't mind swapping [this](https://github.com/webpack/tapable/blob/master/lib/Tapable.js#L295) out. If a simple PR doing just this would be accepted I wouldn't mind making it. However if you want to a benchmark system to hook into the webpack source I'd be very interested in that, but would probably need some help getting off the ground as I'm not yet familiar with the (new?) benchmarking system in webpack source. In the mean time, I'll be reading webpack src!
