### ISSUE TITLE
Is args[args.length - 1] faster than args.pop()/push() ?

### ISSUE THREAD

**Issue by chinesedfan** [webpack/tapable#28]
I notice that only `applyPluginsParallelBailResult` updates args[args.length - 1] directly. And other methods, like `applyPluginsAsync/applyPluginsAsyncSeriesBailResult/applyPluginsParallel`, pop the last argument first, then push a new one.

Shall we always use the faster one?

**Comment by domfarolino** [comment]
Maybe make a perf test + PR? That is kind odd, unless I'm missing something

**Comment by chinesedfan** [comment]
It's easy to understand which one is faster. You can try [this simple perf test](https://jsperf.com/tapable-28) .
