### ISSUE TITLE
is there something missed

### ISSUE THREAD

**Issue by AsJoy** [webpack/tapable#40]
```
exports.AsyncSequencialHook = require("./AsyncSequencialHook");
exports.AsyncSequencialBailHook = require("./AsyncSequencialBailHook");
exports.AsyncWaterfallHook = require("./AsyncWaterfallHook");
```

**Comment by pigcan** [comment]
AsyncSequencialHook => AsyncSeriesLoopHook
AsyncSequencialBailHook => AsyncSeriesBailHook
AsyncWaterfallHook => AsyncSeriesWaterfallHook

AsyncSeriesLoopHook is missed. And I find the `AsyncSeriesLoopHook` hook have some bugs. Maybe it‘s the reason why it’s not be exported right now.

**Comment by sokra** [comment]
Yep send a PR to fix the bugs and export the Hook

**Comment by pigcan** [comment]
OK, @sokra  Later (around this week or next week) I will work on it.

**Comment by sokra** [comment]
I've done it.

**Comment by pigcan** [comment]
@sokra `HookCodeFactory` looks great than before !
