### ISSUE TITLE
Typings questions

### ISSUE THREAD

**Issue by colelawrence** [webpack/tapable#43]
I'm currently working on typing the tapable library, and so far it is going well, but I'm running across some differences between the tests and the documentation. It would be great to get some guidance on some of the really obfuscated aspects of the compiler.

So, to start off with, I have just a couple questions:

 1. What is the `Result` type which @sokra documented in the README as the return values of calls? In my tests, I'm consistently getting undefined returns from `console.log({result: hook.call()});` in the Hook.js test file.
 2. Should users pass in the `type: "sync" | "async" | "promise"` option when creating hooks? It will either greatly complicate (or makes the types less accurate depending on direction) when someone can use `Hookable::tap({name: "SomePlugin", type: "promise"}, callback)` [to declare tap type as "promise"](https://github.com/webpack/tapable/blob/6b91ca9e94cf032420a57a2d0b82b627462b5c1c/lib/Hook.js#L69) rather than `Hookable::tapPromise("SomePlugin", callback)` as in these cases we'd want both `callback` instances to be the inferred to the same type...

@sokra, thank you for updating the readme with some basic interfaces a couple weeks ago, it really helped me start off with a lot of momentum.

Thank you!

**Comment by colelawrence** [comment]
One more question:
 3. What is the difference between interfaces between the AsyncHooks and SyncHook instances? Can you use `call()` and `tap()` on async hooks? Then you can use callAsync/promise and tapAsync/tapPromise on either SyncHooks or AsyncHooks?

Also, does it sound like I'm missing something to understand about parallel or series async hooks? Like, does `TapOptions::before` or `TapOptions::stage` make a difference in parallel hooks?

Thank you!

**Comment by TheLarkInn** [comment]
cc @sokra, when I also get a chance Cole, I'll also share some details. Thanks for deciding to take this on.

**Comment by colelawrence** [comment]
@sokra @TheLarkInn I'm sorry to say that I do not think that my initial approach to generating these types did not go so well. I think the number of unions required to support 4+ arguments is either unmanageable by the TypeScript Language Server, or there is some fatal flaw in the approach.

I think the best I can come up with right now, would be to either create a small wrapper around tapable for people who absolutely need the strict typing which accepts a single argument in the form of an object, so that you can type the object and use the `keyof` helper for the arg names array.

For example, we could declare a `SyncHook` wrapper like so:

```typescript
const { SyncHook } = require("../lib");

type ISyncHook = { _args: string[] } & any

export class TSyncHook<Args extends object, Context={}> {
	_mapIn: (args: Args) => any[]
	_mapOut: (argsArr: any[]) => Args
	_syncHook: ISyncHook
	constructor(argsOrHook: (keyof Args)[] | ISyncHook = []) {
		let argArr: string[]
		if (Array.isArray(argsOrHook)) {
			// is args
			this._syncHook = new SyncHook(argsOrHook)
			argArr = argsOrHook
		} else {
			// is synchook
			this._syncHook = argsOrHook
			argArr = this._syncHook._args
		}

		// map args from object to array
		this._mapIn = new Function('a', "\"use strict\";\n" +
			"return [" + argArr.map(key => 'a.' + key).join(',') +
			"]") as any

		// map args from array to object
		this._mapOut = new Function('a', "\"use strict\";\n" +
			"return {" + argArr.map((key, idx) => `${key}: a[${idx}]`).join(',') +
			"}") as any
	}

	call(args: Args) {
		return this._syncHook.call(...this._mapIn(args))
	}

	tap(name: string, listener: (args: Args) => void) {
		return this._syncHook.tap({ name }, (...args: any[]) => listener(this._mapOut(args)))
	}
}

class Car {
	hooks = {
		accelerate: new TSyncHook<{ newSpeed: number }>(["newSpeed"]),
		break: new TSyncHook<{ isBreaking: boolean }>(["isBreaking"]),
	}

	showBrakeLights: boolean

	/* ... */
}

const myCar = new Car()

myCar.hooks.break.tap("BrakeLightPlugin", ({ isBreaking }) => {
	myCar.showBrakeLights = isBreaking
})

myCar.hooks.accelerate.tap("SpeedDisplayPlugin", ({ newSpeed }) => {
	console.log("New speed", newSpeed)
})

console.log(myCar)
console.log(myCar.hooks.accelerate._mapIn)
console.log(myCar.hooks.accelerate._mapOut)
console.log(myCar.hooks.accelerate._syncHook)

myCar.hooks.accelerate.call({newSpeed: 12})
myCar.hooks.accelerate.call({newSpeed: 20})
```

Maybe there are some better ideas out there, but I'm just not seeing a way to make argument types work at this time.

**Comment by Hoten** [comment]
@colelawrence , your wrapper idea is working great for my project. Thanks for sharing it!
