### ISSUE TITLE
Doesn't work with IE11 (ducks for cover)

### ISSUE THREAD

**Issue by wmertens** [webpack/tapable#50]
I am using this in an SPA and it's really great, but it turns out that the npm version uses `class` in the JS, so it's not ES5. 

Would it be possible to provide the npm code as ES5 code? I don't know what the current best way to provide ES6 code is, but this is the only package that causes problems in the build for our IE users.

In the meantime I'll try some workaround like forcing a babel compilation of this package.

**Comment by ooflorent** [comment]
I don't understand, are you shipping `tapable` into your bundle? `tapable` is just an utility used within webpack and its loaders/plugins. Could you detail what you are trying to achieve?

**Comment by wmertens** [comment]
Yes, I'm using it client-side to have a pluggable framework. It works great
for that…

**Comment by ooflorent** [comment]
Since the library is targeting node 6+, I don't think we would transpile it. Your best option is to include it into your `babel-loader` (instead of `exclude: /node_modules/`).

**Comment by wmertens** [comment]
Yes, I'm whitelisting it now. Fair enough, thanks!
