### ISSUE TITLE
Tapable.plugin deprecation

### ISSUE THREAD

**Issue by mobilutz** [webpack/tapable#56]
I updated webpack on my application and have these deprecation warnings now in my app:
```
(node:48495) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

I did find out, that this package raises them, but couldn't find where they originated, meaning which other package might use Tapable wrong.

Can you give me some hints how I can best trace the packages down?

**Comment by ooflorent** [comment]
Add `process.traceDeprecation = true` to your webpack config to see the full stack trace.
You could also pass a flag to node:

```
node --trace-deprecation ./node_modules/.bin/webpack …
```

**Comment by mobilutz** [comment]
👍  Thank you very much for the hint.
I also found the problematic package.
