### ISSUE TITLE
Feature request: method to remove a tap

### ISSUE THREAD

**Issue by jedwards1211** [webpack/tapable#75]
(I may make a PR for this eventually)
I know that `tapable` is mainly intended for plugins that are registered once at startup.  But this is the first package I turn to when I need something more powerful than an `EventEmitter`, since I can't do anything like an `AsyncSeriesHook` with `EventEmitter`.  Overall it's a pretty good general-purpose replacement.
However, one thing `EventEmitter` can do that `tapable` can't is remove hooks.  I have a few use cases where I would like to use `tapable` but I need to be able to remove the hooks at certain times.

**Comment by ooflorent** [comment]
Have you read this issue #71? One of the goal of tapable is to compile a static event emitter: callbacks are added to the hook and then the hook is _called_. If you add/remove callbacks, the hook must be compiled again and V8 has to reoptimize it.

I don't know what your use-case is but maybe [`async`](https://github.com/caolan/async) would be a better choice.

**Comment by jedwards1211** [comment]
Yeah that's a good point, I had forgotten about that aspect of Tapable.  It's not that hard for me to
```js
for (let listener of listeners) {
  await listener(foo, bar)
}
```
I just was looking for a preexisting class that manages the listener list itself.
So I guess I'll just write my own class to do it.
Thanks!
