### ISSUE TITLE
Can you confirm that the license for v1.0 is also MIT?

### ISSUE THREAD

**Issue by spectejb** [webpack/tapable#76]
- The master branch is MIT (https://github.com/webpack/tapable/blob/master/LICENSE)
- v1.1 is MIT (https://github.com/webpack/tapable/blob/v1.1.0/LICENSE)

For some reason, v1.0 goes to "page not found" (https://github.com/webpack/tapable/tree/v1.0.0/LICENSE)

**Comment by newyork-anthonyng** [comment]
The `LICENSE` file wasn't added until `v1.1.0`. But the `package.json` in `v1.0.0` does show `MIT` in its license field.

https://github.com/webpack/tapable/blob/v1.0.0/package.json#L6

**Comment by sokra** [comment]
yep it's MIT
