### ISSUE TITLE
Way to tap before other taps?  Are `stage` and `before` options supported?

### ISSUE THREAD

**Issue by cspotcode** [webpack/tapable#86]
We're thinking about using tapable as a replacement for typedoc's internal eventing stuff.  Is there a way to `tap` a hook before other already-registered taps?  I see Hook options `before` and `stage`.  Are they supported, or will they go away when v2 is released?  If we start using tapable, should we use the v2 beta or stick to v1?

Thanks for any insight you can offer.  Let me know if I should be looking elsewhere for answers.

**Comment by ooflorent** [comment]
`before` and `stage` are safe to use. We do not intent to deprecate or remove them. 

However, before using `tapable`, **please make sure you understand the library limitations**. `tapable` is designed to produce _static event dispatchers_ (hooks). Which means that you must subscribe (`tap`) and then fire the event (`call`).

- You cannot unregister a listener
- You should add **all** the listeners before using `call`

**Comment by cspotcode** [comment]
Thank you for clarifying, that's good to know.  I think it should work for us; we want to support a composable, pluggable architecture, very similar to webpack.

The dispatchers are static because it's faster, right?

**Comment by ooflorent** [comment]
> The dispatchers are static because it's faster, right?

That's debatable but yes. A compiled hook should be faster than a polymorphic function. There are 2 ways to compile a hook:

- call `call*` (which call `compile`)
- call `compile`

If you look at execution times, the time spent in `compile` + `call` + the handlers will probably be bigger than a traditional event emitter. But if you compile your hooks upfront, then the handlers should be faster.

Under the hook, tapable _compiles_ this:

```js
listeners.forEach(listener => {
  listener(...args)
})
```

into this:

```js
listeners[0](_0, _1, _2)
…
listeners[13](_0, _1, _2)
```

**Comment by sokra** [comment]
We always preferred `stage` over `before`. I found it easier to work with.

**Comment by cspotcode** [comment]
Is there documentation or an example of using `stage`?  I'm having trouble understanding how to use it, and neither type declarations have JSDoc comments to explain.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/tapable/index.d.ts#L244
https://github.com/webpack/tapable/blob/master/tapable.d.ts#L30

**Comment by sokra** [comment]
It's a number, Taps with lower number execute before Taps with higher number. Taps with equal stage execute in order of attaching.

**Comment by cspotcode** [comment]
Very cool, I can declare multiple stages of a hook using a numeric enumeration, and then plugins can tap into any stage by name.

Thanks for all the information; this is very helpful.
