### ISSUE TITLE
Just curious why do "new Function(code)" ?

### ISSUE THREAD

**Issue by yanche** [webpack/tapable#90]
Hey I was looking at the source today just curious why it constructs code from taps in string then do "new Function".
Is it about perf ? How much it wins over plain code ?

**Comment by newyork-anthonyng** [comment]
@yanche Does #62 answer your question?

**Comment by evilebottnawi** [comment]
Yep, answer above

**Comment by yanche** [comment]
Yup I think it does. thanks @newyork-anthonyng 👍
