### ISSUE TITLE
tapPromise doesn't return my resolved value

### ISSUE THREAD

**Issue by zzs1020** [webpack/tapable#91]
Hi, there,

Thanks for the awesome jobs. I encountered an issue while trying to use tapPromise. I'm using version 1.1.1

if I use my defined plugin this way:
```javascript
xx.hooks.endpoint.tapPromise('EndpointPlugin', (options) => {
      return new Promise(resolve => {
        setTimeout(() => {
          resolve({ retcode: 0, res: { msg: 'hello world' } });
        }, 0);
      }).then(res => {
        return res;
      })
    });
```
with 
```javascript
  request(options) {
    return this.hooks.endpoint.promise(options).then((res) => {
    // **res is undefined!**
      return res;
    });
  }
```
res is not returned by tapPromise.

But if I change my code to following;
```javascript
xx.hooks.endpoint.tapPromise('EndpointPlugin', (options, result) => {
      return new Promise(resolve => {
        setTimeout(() => {
          resolve({ retcode: 0, res: { msg: 'hello world' } });
        }, 0);
      }).then(res => {
        result.res = res;
        return res;
      })
    });
```
with
```javascript
 request(options) {
    const result = {};
    return this.hooks.endpoint.promise(options, result).then((res) => {
      return result.res;
    });
  }
```
I still can't get res of course, but with this workaround, I can at least get what I wanted. I saw this is also the way noted on your README(google map ROUTE example).

I'm wondering if you designed it this way or this is a bug? because the usage is weird, I have to define an additional 'container variable' all the time, which actually means nothing to users.

---------- new input after 1 day ------------
this also happens to tap(), for example:
```js
myCar.hooks.accelerate.tap("LoggerPlugin", newSpeed => {return newSpeed === 5;});
```
```
setSpeed(newSpeed) {
    // returned value is still undefined!
    const value = this.hooks.accelerate.call(newSpeed);
    return value;
}
```
I looked code, seems they all are using _tap(), so the behavior may happen on all of them. I'll try looking code and make changes and PR, but your help is definitely better! thanks.

**Comment by evilebottnawi** [comment]
Feel free to send a PR with fix

**Comment by zzs1020** [comment]
my bad, I just realized that I should use **AsyncSeriesWaterfallHook** and **SyncWaterfallHook** for async hooks and sync hooks if I want tapPromise and tap **return values**!
