### ISSUE TITLE
Where do I find docs on how to upgrade a plugin to the  new API on `.hooks`?

### ISSUE THREAD

**Issue by givanse** [webpack/tapable#94]
> (node:10572) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

Search results only show answers for:

> Q: My app broke, please help.
> A: Upgrade a webpack plugin from v1 to v2.

As a plugin ~author~ heir, where do I find docs on the upgrade process?

**Comment by evilebottnawi** [comment]
@givanse please open this issue in `webpack-docs` repo, thanks

**Comment by givanse** [comment]
moved to: https://github.com/webpack/webpack.js.org/issues/2926
